### ISSUE TITLE
Support array of strings

### ISSUE THREAD

**Issue by iddan** [blakeembrey/change-case#123]
I find myself repeating code like:
```javascript
camelCaes(["foo", "bar"].join(" ")) // => "fooBar"
```
I wonder can the library support the call:
```javascript
camelCase(["foo", "bar"]) // => "fooBar"
```

**Comment by blakeembrey** [comment]
This won't be supported as-is because this library does a bunch of extra stuff and I expect there will be bugs filed against the behavior on arrays. That said, why don't you just do `camelCase` without this library? It'd be much simpler and more performant, e.g. `x[0].toLowerCase() + x.slice(1).map(x => x[0].toUpperCase() + x.slice(1).toLowerCase()).join('')`?

**Comment by iddan** [comment]
I want to abstract this kind of code
