### ISSUE TITLE
First word after colon not capitalized

### ISSUE THREAD

**Issue by mohd-akram** [blakeembrey/change-case#323]
```javascript
titleCase("cowboy bebop: the movie")
```

Expected:

Cowboy Bebop: The Movie

Actual:

Cowboy Bebop: the Movie

[Source](https://twitter.com/APStylebook/status/1021397036808265729)

**Comment by blakeembrey** [comment]
Fixed with [4.2.0](https://github.com/blakeembrey/change-case/releases/tag/title-case%404.2.0). It ended up being a bit messier and more complex than I expected because I didn't currently have any sort of "end of sentence" handling, which I assume is also a bug (i.e. `cowboy bebop. the movie.` should presumably do the same thing).

**Comment by mohd-akram** [comment]
Thanks for the prompt fix! Tested it and it works well. Great that the general case is now handled as well.
